# Generated by Django 5.1.3 on 2024-11-13 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='Adress',
            new_name='Address',
        ),
    ]
